spring:
    flyway:
        enabled: true
        url: "jdbc:mysql://localhost:3306/test_jdbc?serverTimezone=GMT%2B8"
        user: "root"
        password: "123qwertyA"
        baseline-on-migrate: true
    datasource:
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/test_jdbc?serverTimezone=GMT%2B8"
        password: "123qwertyA"
        username: "root"
        type: com.alibaba.druid.pool.DruidDataSource
        hikari:
            maximum-pool-size: 10
        dbcp2:
            max-total: 10
        druid:
            driver-class-name: "com.mysql.cj.jdbc.Driver"
            url: "jdbc:mysql://localhost:3306/test_jdbc?serverTimezone=GMT%2B8"
            username: "root"
            password: "123qwertyA"
            max-active: 10